#!/usr/bin/env python
# Copyright 2005 (C) Sune Kirkeby -- Licensed under the "X11 License"

from ibofobi.utils.test import munge
munge.munge_settings()
munge.munge_db_db()

from django.conf import settings
from ibofobi.utils.test.test_app import test_app
for app in settings.INSTALLED_APPS:
    test_app(app)
